name: Meu Primeiro WorkFlow no Guthub Actions

on:

  push:
    branches: [ "main" ]
 
jobs:
  test-job: 
    name: Executando Job teste
    runs-on: self-hosted
    steps:
      - name: Step 1
        uses: actions/checkout@v4
      
      - name: Docker Login
 
        uses: docker/login-action@v3.4.0
        with:
  
            username: 'gabriellsantoss'
            password: '${{secrets.SECRET}}'
  

      
