name: Meu Primeiro WorkFlow no Guthub Actions

on:

  push:
    branches: [ "main" ]
 
jobs:
  test-job: 
    name: Executando Job teste
    runs-on: self-hosted
    steps:
      - name: Step 1
        uses: actions/checkout@v4
      
      - name: Step 2
        run: echo Hello, world!

      - name: Step 3
        run: echo Hello, world Step 3!

      - name: Step 4
        run: echo Hello, world Step 4!

      